version: '3'
services:
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: blue_nginx_container
        restart: unless-stopped
        tty: true
        ports:
          - "7070:80"
          - "443:443"
        volumes:
          - ./src:/var/www/
          - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
          - app

    #PHP Service
    app:
        build: .docker/php
        container_name: blue_app_container
        volumes:
          - ./src:/var/www/
          - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped
        tty: true
        environment:
          - maildev_host=blue_maildev_container
            #SERVICE_NAME: app
            #SERVICE_TAGS: dev          
        working_dir: /var/www
        depends_on:
          - maildev
          - mysql   
           
    #MySQL Service
    mysql:
        image: mysql:8
        container_name: blue_mysql_container
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
            
    #PHP-MyAdmin MYSQL
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: blue_phpmyadmin_container
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 7071:80
        links:
            - mysql

    #Mail_Host
    maildev:
        image: djfarrelly/maildev
        container_name: blue_maildev_container
        ports:
          - 7072:80